import { ArrowLeft, CheckCircle } from "lucide-react";
import { useState, useEffect } from "react";
import { useAppContext } from "../../context/AppContext";
import { api, type LoanQuote, ApiError } from "../../api/client";
import { env } from "../../config/env";
import { localQuote } from "../../lib/pricing";
import { getLoanDraft } from "../../lib/selection";
interface Props { onNavigate: (s: string) => void; }
function ugx(n: number) { return "UGX " + Math.round(n).toLocaleString("en-UG"); }
export function LoanReviewScreen({ onNavigate }: Props) {
 const { state }=useAppContext(); const token=state.session.token; const draft=getLoanDraft(); const [agreed,setAgreed]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [quoteError,setQuoteError]=useState(""); const [quoteLoading,setQuoteLoading]=useState(env.USE_API);
 const fallbackAmount=draft?.amount??50000, fallbackTerm=draft?.termDays??90; const [quote,setQuote]=useState<LoanQuote|null>(()=>env.USE_API?null:localQuote(fallbackAmount,fallbackTerm,0));
 useEffect(()=>{let active=true;if(!draft)return()=>{active=false};if(!env.USE_API){setQuote(localQuote(draft.amount,draft.termDays,0));setQuoteLoading(false);return()=>{active=false}}if(!token){setQuote(null);setQuoteError("Your session is not available. Sign in again before reviewing this application.");setQuoteLoading(false);return()=>{active=false}}setQuoteLoading(true);setQuoteError("");api.quoteLoan(token,draft.amount,draft.termDays).then(v=>{if(active)setQuote(v)}).catch(e=>{if(active)setQuoteError(e instanceof Error?e.message:"Could not load the authoritative Kuula quote.")}).finally(()=>{if(active)setQuoteLoading(false)});return()=>{active=false}},[token,draft?.amount,draft?.termDays]);
 if(!draft)return <div style={{height:"100%",display:"grid",placeItems:"center",padding:24}}><div><h2>Application details expired</h2><button className="kuula-primary" onClick={()=>onNavigate("loan-apply")}>Return to Application</button></div></div>;
 const submit=async()=>{if(!agreed||loading||!token||!quote||quoteLoading||quoteError)return;setError("");setLoading(true);if(env.USE_API){try{await api.submitApplication(token,draft);onNavigate("loan-approval")}catch(e){setError(e instanceof ApiError?e.message:"Could not submit your application.")}finally{setLoading(false)}return}setTimeout(()=>{setLoading(false);onNavigate("loan-approval")},500)};
 const Row=({label,value,bold}:{label:string;value:string;bold?:boolean})=><div style={{display:"flex",justifyContent:"space-between",gap:12,padding:"9px 0",borderBottom:"1px solid #EEF2EF"}}><span style={{fontSize:12,color:"#68766F"}}>{label}</span><span style={{fontSize:12,fontWeight:bold?800:600,color:bold?"#0B5E3A":"#1F2937",textAlign:"right"}}>{value}</span></div>;
 const canSubmit=Boolean(agreed&&!loading&&token&&quote&&!quoteLoading&&!quoteError);
 return <div style={{display:"flex",flexDirection:"column",height:"100%",background:"#F7FAF8"}}><div style={{display:"flex",alignItems:"center",padding:16,background:"linear-gradient(135deg,#0B5E3A,#087148)"}}><button onClick={()=>onNavigate("loan-apply")} style={{width:36,height:36,borderRadius:10,border:0,background:"rgba(255,255,255,.2)"}}><ArrowLeft size={18} color="white"/></button><div style={{marginLeft:12,color:"white"}}><strong>Review Application</strong><div style={{fontSize:11,opacity:.8}}>Confirm the information sent for underwriting</div></div></div>
 <div style={{flex:1,overflowY:"auto",padding:"20px 16px 150px",display:"flex",flexDirection:"column",gap:16}}>
  <div style={{background:"#EDF8F2",borderRadius:16,padding:16,border:"1px solid #B7DEC9"}}><small>REQUESTED AMOUNT</small><p style={{fontSize:34,fontWeight:900,color:"#0B5E3A",margin:0}}>{ugx(draft.amount)}</p><small>{draft.termDays}-day term · {draft.purpose} · {draft.channel}</small></div>
  <div style={{background:"white",borderRadius:16,padding:16}}><strong>Employment & livelihood</strong><Row label="Status" value={draft.employmentStatus}/><Row label="Occupation / activity" value={draft.occupationOrBusiness}/><Row label="Employer / business" value={draft.employerOrBusinessName||"Not applicable"}/><Row label="Time in work / business" value={draft.workDuration}/><Row label="Primary income source" value={draft.incomeSource}/><Row label="Primary repayment source" value={draft.repaymentSource}/></div>
  <div style={{background:"white",borderRadius:16,padding:16}}><strong>Affordability declaration</strong><Row label="Monthly income" value={ugx(draft.declaredMonthlyIncome)}/><Row label="Monthly expenses" value={ugx(draft.declaredMonthlyExpenses)}/><Row label="Existing monthly debt" value={ugx(draft.existingDebtPayment)}/><p style={{fontSize:11,color:"#68766F"}}>These declarations do not guarantee approval. Kuula also uses current KYC, credit evidence and server-side affordability checks.</p></div>
  <div style={{background:"white",borderRadius:16,padding:16}}><strong>Repayment disclosure</strong>{quoteLoading&&<p>Loading Kuula’s current server quote…</p>}{quoteError&&<p role="alert" style={{color:"#B91C1C"}}>{quoteError}</p>}{quote&&<><Row label="Principal" value={ugx(quote.principal)}/><Row label={`Interest (${quote.aprPercent}% APR, simple)`} value={ugx(quote.interest)}/><Row label="Service fee" value={ugx(quote.fee)}/><Row label="Total cost of credit" value={ugx(quote.interest+quote.fee)}/><Row label="Total repayment" value={ugx(quote.total)} bold/></>}</div>
  <button disabled={!quote||quoteLoading||Boolean(quoteError)} onClick={()=>setAgreed(!agreed)} style={{display:"flex",gap:12,background:agreed?"#F0FDF4":"#FFF",border:`1.5px solid ${agreed?"#0B5E3A":"#DDE5E0"}`,borderRadius:12,padding:14,textAlign:"left"}}><div style={{width:22,height:22,borderRadius:6,border:"2px solid #0B5E3A",background:agreed?"#0B5E3A":"transparent",display:"grid",placeItems:"center"}}>{agreed&&<CheckCircle size={14} color="white"/>}</div><p style={{fontSize:12,margin:0}}>I confirm that my application, livelihood and affordability information is accurate. I understand this is a credit application and not a guarantee of approval or a loan agreement.</p></button>
 </div><div style={{position:"absolute",bottom:0,left:0,right:0,padding:"10px 16px 36px",background:"white",borderTop:"1px solid #E8EEEA"}}>{error&&<p style={{fontSize:12,color:"#B91C1C",textAlign:"center"}}>{error}</p>}<button onClick={submit} disabled={!canSubmit} className="kuula-primary" style={{width:"100%",height:52,opacity:canSubmit?1:.55}}>{loading?"Submitting…":quoteLoading?"Loading Quote…":"Submit Credit Application"}</button></div></div>;
}
