/**
 * Screen registry — maps every screen id to a lazily-loaded component and an
 * access level used by the router guards.
 */
import type { ComponentType, LazyExoticComponent } from "react";
import { lazy } from "react";

export type ScreenAccess = "public" | "customer" | "admin";

export interface ScreenProps {
  onNavigate: (screenId: string) => void;
}

interface ScreenEntry {
  access: ScreenAccess;
  load: () => Promise<{ default: ComponentType<ScreenProps> }>;
}

const SCREENS: Record<string, ScreenEntry> = {
  "language": { access: "public", load: () => import("../components/screens/LanguageScreen").then((m) => ({ default: m.LanguageScreen })) },
  "onboarding": { access: "public", load: () => import("../components/screens/OnboardingScreen").then((m) => ({ default: m.OnboardingScreen })) },
  "welcome": { access: "public", load: () => import("../components/screens/WelcomeScreen").then((m) => ({ default: m.WelcomeScreen })) },
  "create-account": { access: "public", load: () => import("../components/screens/CreateAccountScreen").then((m) => ({ default: m.CreateAccountScreen })) },
  "kyc": { access: "public", load: () => import("../components/screens/KycScreen").then((m) => ({ default: m.KycScreen })) },
  "phone-verify": { access: "public", load: () => import("../components/screens/PhoneVerifyScreen").then((m) => ({ default: m.PhoneVerifyScreen })) },
  "biometric-setup": { access: "public", load: () => import("../components/screens/BiometricSetupScreen").then((m) => ({ default: m.BiometricSetupScreen })) },
  "home": { access: "customer", load: () => import("../components/screens/HomeScreen").then((m) => ({ default: m.HomeScreen })) },
  "dashboard": { access: "customer", load: () => import("../components/screens/DashboardScreen").then((m) => ({ default: m.DashboardScreen })) },
  "loan-calculator": { access: "customer", load: () => import("../components/screens/DashboardScreen").then((m) => ({ default: m.DashboardScreen })) },
  "quick-actions": { access: "customer", load: () => import("../components/screens/QuickActionsScreen").then((m) => ({ default: m.QuickActionsScreen })) },
  "loan-apply": { access: "customer", load: () => import("../components/screens/LoanApplyScreen").then((m) => ({ default: m.LoanApplyScreen })) },
  "loan-purpose": { access: "customer", load: () => import("../components/screens/LoanPurposeScreen").then((m) => ({ default: m.LoanPurposeScreen })) },
  "loan-disbursement": { access: "customer", load: () => import("../components/screens/LoanDisbursementScreen").then((m) => ({ default: m.LoanDisbursementScreen })) },
  "loan-review": { access: "customer", load: () => import("../components/screens/LoanReviewScreen").then((m) => ({ default: m.LoanReviewScreen })) },
  "loan-approval": { access: "customer", load: () => import("../components/screens/LoanApprovalScreen").then((m) => ({ default: m.LoanApprovalScreen })) },
  "loan-detail": { access: "customer", load: () => import("../components/screens/LoanDetailScreen").then((m) => ({ default: m.LoanDetailScreen })) },
  "loan-history": { access: "customer", load: () => import("../components/screens/LoanHistoryScreen").then((m) => ({ default: m.LoanHistoryScreen })) },
  "loan-schedule": { access: "customer", load: () => import("../components/screens/LoanScheduleScreen").then((m) => ({ default: m.LoanScheduleScreen })) },
  "make-payment": { access: "customer", load: () => import("../components/screens/MakePaymentScreen").then((m) => ({ default: m.MakePaymentScreen })) },
  "payment-confirm": { access: "customer", load: () => import("../components/screens/ConfirmScreen").then((m) => ({ default: m.ConfirmScreen })) },
  "loan-agreement": { access: "customer", load: () => import("../components/screens/LoanAgreementScreen").then((m) => ({ default: m.LoanAgreementScreen })) },
  "wallet": { access: "customer", load: () => import("../components/screens/WalletOverviewScreen").then((m) => ({ default: m.WalletOverviewScreen })) },
  "add-payment-method": { access: "customer", load: () => import("../components/screens/AddPaymentMethodScreen").then((m) => ({ default: m.AddPaymentMethodScreen })) },
  "payment-methods-list": { access: "customer", load: () => import("../components/screens/PaymentMethodsListScreen").then((m) => ({ default: m.PaymentMethodsListScreen })) },
  "transaction-history": { access: "customer", load: () => import("../components/screens/TransactionHistoryScreen").then((m) => ({ default: m.TransactionHistoryScreen })) },
  "transaction-detail": { access: "customer", load: () => import("../components/screens/TransactionDetailScreen").then((m) => ({ default: m.TransactionDetailScreen })) },
  "credit-dashboard": { access: "customer", load: () => import("../components/screens/CreditDashboardScreen").then((m) => ({ default: m.CreditDashboardScreen })) },
  "credit-breakdown": { access: "customer", load: () => import("../components/screens/CreditBreakdownScreen").then((m) => ({ default: m.CreditBreakdownScreen })) },
  "improve-credit": { access: "customer", load: () => import("../components/screens/ImproveCreditScreen").then((m) => ({ default: m.ImproveCreditScreen })) },
  "notifications": { access: "customer", load: () => import("../components/screens/NotificationsListScreen").then((m) => ({ default: m.NotificationsListScreen })) },
  "notification-detail": { access: "customer", load: () => import("../components/screens/NotificationDetailScreen").then((m) => ({ default: m.NotificationDetailScreen })) },
  "settings": { access: "customer", load: () => import("../components/screens/SettingsScreen").then((m) => ({ default: m.SettingsScreen })) },
  "profile": { access: "customer", load: () => import("../components/screens/ProfileScreen").then((m) => ({ default: m.ProfileScreen })) },
  "personal-info": { access: "customer", load: () => import("../components/screens/PersonalInfoScreen").then((m) => ({ default: m.PersonalInfoScreen })) },
  "notification-settings": { access: "customer", load: () => import("../components/screens/NotificationSettingsScreen").then((m) => ({ default: m.NotificationSettingsScreen })) },
  "privacy-security": { access: "customer", load: () => import("../components/screens/PrivacySecurityScreen").then((m) => ({ default: m.PrivacySecurityScreen })) },
  "help-support": { access: "customer", load: () => import("../components/screens/HelpSupportScreen").then((m) => ({ default: m.HelpSupportScreen })) },
  "contact-support": { access: "customer", load: () => import("../components/screens/ContactSupportScreen").then((m) => ({ default: m.ContactSupportScreen })) },
  "about-app": { access: "customer", load: () => import("../components/screens/AboutAppScreen").then((m) => ({ default: m.AboutAppScreen })) },
  "logout-confirm": { access: "customer", load: () => import("../components/screens/LogoutConfirmScreen").then((m) => ({ default: m.LogoutConfirmScreen })) },
  "delete-account": { access: "customer", load: () => import("../components/screens/DeleteAccountScreen").then((m) => ({ default: m.DeleteAccountScreen })) },
  "customer-officer-assigned": { access: "customer", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.CustomerOfficerAssignedScreen })) },
  "loan-timeline": { access: "customer", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.CustomerLoanTimelineScreen })) },
  "user-support-chat": { access: "customer", load: () => import("../components/screens/UserSupportChatScreen").then((m) => ({ default: m.UserSupportChatScreen })) },
  "customer-support-chat": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerSupportChatScreen })) },
  "customer-chat-history": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerChatHistoryScreen })) },
  "customer-create-ticket": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerCreateTicketScreen })) },
  "customer-ticket-status": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerTicketStatusScreen })) },
  "customer-ticket-details": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerTicketDetailsScreen })) },
  "customer-whatsapp-support": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerWhatsAppSupportScreen })) },
  "customer-phone-support": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerPhoneSupportScreen })) },
  "customer-email-support": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerEmailSupportScreen })) },
  "customer-faq": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerFAQScreen })) },
  "customer-faq-detail": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerFAQDetailScreen })) },
  "customer-loan-guides": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerLoanGuidesScreen })) },
  "customer-how-to-pay": { access: "customer", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.CustomerHowToPayScreen })) },
  "customer-available-promotions": { access: "customer", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.CustomerAvailablePromotionsScreen })) },
  "customer-claim-promotion": { access: "customer", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.CustomerClaimPromotionScreen })) },
  "customer-notif-history": { access: "customer", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.CustomerNotifHistoryScreen })) },
  "customer-autopay-setup": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerAutoPaySetupScreen })) },
  "customer-autopay-settings": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerAutoPaySettingsScreen })) },
  "customer-autopay-history": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerAutoPayHistoryScreen })) },
  "customer-autopay-failure": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerAutoPayFailureScreen })) },
  "customer-autopay-link": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerAutoPayLinkScreen })) },
  "customer-autopay-notification": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerAutoPayNotificationScreen })) },
  "customer-repayment-offer": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerRepaymentOfferScreen })) },
  "customer-accept-plan": { access: "customer", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.CustomerAcceptPlanScreen })) },
  "customer-disbursement-status": { access: "customer", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.CustomerDisbursementStatusScreen })) },
  "customer-loan-rejection": { access: "customer", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.CustomerLoanRejectionScreen })) },
  "customer-credit-limit-increase": { access: "customer", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.CustomerCreditLimitIncreaseScreen })) },
  "customer-loan-refinance": { access: "customer", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.CustomerLoanRefinanceScreen })) },
  "customer-reverify-identity": { access: "customer", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.CustomerReverifyIdentityScreen })) },
  "customer-privacy-policy": { access: "public", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.CustomerPrivacyPolicyScreen })) },
  "customer-terms": { access: "public", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.CustomerTermsScreen })) },
  "admin-login": { access: "public", load: () => import("../components/screens/AdminLoginScreen").then((m) => ({ default: m.AdminLoginScreen })) },
  "admin-otp": { access: "public", load: () => import("../components/screens/AdminOTPScreen").then((m) => ({ default: m.AdminOTPScreen })) },
  "admin-dashboard": { access: "admin", load: () => import("../components/screens/AdminDashboardScreen").then((m) => ({ default: m.AdminDashboardScreen })) },
  "admin-quick-stats": { access: "admin", load: () => import("../components/screens/AdminQuickStatsScreen").then((m) => ({ default: m.AdminQuickStatsScreen })) },
  "admin-loan-apps": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminLoanAppsListScreen })) },
  "admin-loan-app-detail": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminLoanAppDetailScreen })) },
  "admin-loan-approval": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminLoanApprovalScreen })) },
  "admin-loan-rejection": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminLoanRejectionScreen })) },
  "admin-active-loans": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminActiveLoansListScreen })) },
  "admin-active-loan-detail": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminActiveLoanDetailScreen })) },
  "admin-repayment-tracking": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminRepaymentTrackingScreen })) },
  "admin-overdue-loans": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminOverdueLoansListScreen })) },
  "admin-overdue-detail": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminOverdueLoanDetailScreen })) },
  "admin-loan-history": { access: "admin", load: () => import("../components/screens/AdminLoanScreens").then((m) => ({ default: m.AdminLoanHistoryAllScreen })) },
  "admin-customer-list": { access: "admin", load: () => import("../components/screens/AdminCustomerScreens").then((m) => ({ default: m.AdminCustomerListScreen })) },
  "admin-customer-detail": { access: "admin", load: () => import("../components/screens/AdminCustomerScreens").then((m) => ({ default: m.AdminCustomerDetailScreen })) },
  "admin-customer-kyc": { access: "admin", load: () => import("../components/screens/AdminCustomerScreens").then((m) => ({ default: m.AdminCustomerKYCScreen })) },
  "admin-customer-risk": { access: "admin", load: () => import("../components/screens/AdminCustomerScreens").then((m) => ({ default: m.AdminCustomerRiskScreen })) },
  "admin-block-customer": { access: "admin", load: () => import("../components/screens/AdminCustomerScreens").then((m) => ({ default: m.AdminBlockCustomerScreen })) },
  "admin-credit-scores": { access: "admin", load: () => import("../components/screens/AdminCreditPaymentScreens").then((m) => ({ default: m.AdminCreditScoresListScreen })) },
  "admin-credit-detail": { access: "admin", load: () => import("../components/screens/AdminCreditPaymentScreens").then((m) => ({ default: m.AdminCreditScoreDetailScreen })) },
  "admin-credit-model": { access: "admin", load: () => import("../components/screens/AdminCreditPaymentScreens").then((m) => ({ default: m.AdminCreditModelScreen })) },
  "admin-all-transactions": { access: "admin", load: () => import("../components/screens/AdminCreditPaymentScreens").then((m) => ({ default: m.AdminAllTransactionsScreen })) },
  "admin-transaction-detail": { access: "admin", load: () => import("../components/screens/AdminCreditPaymentScreens").then((m) => ({ default: m.AdminTransactionDetailScreen })) },
  "admin-payment-processing": { access: "admin", load: () => import("../components/screens/AdminCreditPaymentScreens").then((m) => ({ default: m.AdminPaymentProcessingScreen })) },
  "admin-failed-transactions": { access: "admin", load: () => import("../components/screens/AdminCreditPaymentScreens").then((m) => ({ default: m.AdminFailedTransactionsScreen })) },
  "admin-reports": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminReportsDashboardScreen })) },
  "admin-daily-report": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminDailyReportScreen })) },
  "admin-weekly-report": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminWeeklyReportScreen })) },
  "admin-monthly-report": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminMonthlyReportScreen })) },
  "admin-export-report": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminExportReportScreen })) },
  "admin-settings": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminSettingsScreen })) },
  "admin-loan-products": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminLoanProductsScreen })) },
  "admin-interest-settings": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminInterestSettingsScreen })) },
  "admin-service-fee": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminServiceFeeScreen })) },
  "admin-mtn-api": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminMTNAPIScreen })) },
  "admin-airtel-api": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminAirtelAPIScreen })) },
  "admin-notif-templates": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminNotifTemplatesScreen })) },
  "admin-staff": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminStaffManagementScreen })) },
  "admin-staff-permissions": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminStaffPermissionsScreen })) },
  "admin-compliance": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminComplianceScreen })) },
  "admin-support-inbox": { access: "admin", load: () => import("../components/screens/AdminSupportInboxScreen").then((m) => ({ default: m.AdminSupportInboxScreen })) },
  "admin-tickets": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminTicketsListScreen })) },
  "admin-ticket-detail": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminTicketDetailScreen })) },
  "admin-bulk-sms": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminBulkSMSScreen })) },
  "admin-bulk-email": { access: "admin", load: () => import("../components/screens/AdminReportsSettingsSupportScreens").then((m) => ({ default: m.AdminBulkEmailScreen })) },
  "admin-ticket-reply": { access: "admin", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.AdminTicketReplyScreen })) },
  "admin-ticket-escalation": { access: "admin", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.AdminTicketEscalationScreen })) },
  "admin-support-staff-dashboard": { access: "admin", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.AdminSupportStaffDashboardScreen })) },
  "admin-support-analytics": { access: "admin", load: () => import("../components/screens/ExtraCustomerSupportScreens").then((m) => ({ default: m.AdminSupportAnalyticsScreen })) },
  "admin-approval-workflow": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminApprovalWorkflowScreen })) },
  "admin-approval-levels": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminApprovalLevelsScreen })) },
  "admin-officer-assignment": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminOfficerAssignmentScreen })) },
  "admin-officer-dashboard": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminOfficerDashboardScreen })) },
  "admin-followup-reminder": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminFollowupReminderScreen })) },
  "admin-approval-history": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminApprovalHistoryScreen })) },
  "admin-pending-by-officer": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminPendingByOfficerScreen })) },
  "admin-auto-approve-settings": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminAutoApproveSettingsScreen })) },
  "admin-loan-escalation": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminLoanEscalationScreen })) },
  "admin-approval-time-tracking": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminApprovalTimeTrackingScreen })) },
  "admin-officer-performance": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminOfficerPerformanceScreen })) },
  "admin-officer-contact": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminOfficerContactScreen })) },
  "admin-followup-status": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminFollowupStatusScreen })) },
  "admin-followup-history": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminFollowupHistoryScreen })) },
  "admin-officer-availability": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminOfficerAvailabilityScreen })) },
  "admin-transfer-loan": { access: "admin", load: () => import("../components/screens/ExtraApprovalOfficerScreens").then((m) => ({ default: m.AdminTransferLoanScreen })) },
  "admin-notif-triggers": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminNotifTriggersScreen })) },
  "admin-campaigns-list": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminCampaignsListScreen })) },
  "admin-create-campaign": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminCreateCampaignScreen })) },
  "admin-campaign-targeting": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminCampaignTargetingScreen })) },
  "admin-campaign-dashboard": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminCampaignDashboardScreen })) },
  "admin-bulk-notif": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminBulkNotifScreen })) },
  "admin-payment-reminder-settings": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminPaymentReminderSettingsScreen })) },
  "admin-overdue-notif-settings": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminOverdueNotifSettingsScreen })) },
  "admin-credit-milestone": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminCreditMilestoneScreen })) },
  "admin-promotion-expiry": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminPromotionExpiryScreen })) },
  "admin-notif-analytics": { access: "admin", load: () => import("../components/screens/ExtraNotifPromoScreens").then((m) => ({ default: m.AdminNotifAnalyticsScreen })) },
  "admin-autopay-rules": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminAutoPayRulesScreen })) },
  "admin-collection-schedule": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionScheduleScreen })) },
  "admin-collection-attempt-history": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionAttemptHistoryScreen })) },
  "admin-failed-collection": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminFailedCollectionScreen })) },
  "admin-retry-collection": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminRetryCollectionScreen })) },
  "admin-autopay-analytics": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminAutoPayAnalyticsScreen })) },
  "admin-collection-queue": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionQueueScreen })) },
  "admin-collection-failure-reason": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionFailureReasonScreen })) },
  "admin-collections-dashboard": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionsDashboardScreen })) },
  "admin-call-customer": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCallCustomerScreen })) },
  "admin-call-history": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCallHistoryScreen })) },
  "admin-repayment-negotiation": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminRepaymentNegotiationScreen })) },
  "admin-repayment-plan-detail": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminRepaymentPlanDetailScreen })) },
  "admin-partial-payment": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminPartialPaymentScreen })) },
  "admin-collection-notes": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionNotesScreen })) },
  "admin-collection-priority": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionPriorityScreen })) },
  "admin-escalate-legal": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminEscalateLegalScreen })) },
  "admin-legal-case": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminLegalCaseScreen })) },
  "admin-collections-team-dashboard": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionsTeamDashboardScreen })) },
  "admin-collection-success-rate": { access: "admin", load: () => import("../components/screens/ExtraAutoPayCollectionsScreens").then((m) => ({ default: m.AdminCollectionSuccessRateScreen })) },
  "admin-credit-limit-approval": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminCreditLimitApprovalScreen })) },
  "admin-refinance-approval": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminRefinanceApprovalScreen })) },
  "admin-risk-assessment": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminRiskAssessmentScreen })) },
  "admin-unblock-customer": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminUnblockCustomerScreen })) },
  "admin-fraud-detection": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminFraudDetectionScreen })) },
  "admin-fraud-investigation": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminFraudInvestigationScreen })) },
  "admin-compliance-report": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminComplianceReportScreen })) },
  "admin-data-retention": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminDataRetentionScreen })) },
  "admin-audit-log": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminAuditLogScreen })) },
  "admin-system-health": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminSystemHealthScreen })) },
  "admin-backup-restore": { access: "admin", load: () => import("../components/screens/ExtraCriticalScreens").then((m) => ({ default: m.AdminBackupRestoreScreen })) },
};

export interface RegisteredScreen {
  id: string;
  access: ScreenAccess;
  Component: LazyExoticComponent<ComponentType<ScreenProps>>;
}

export const REGISTERED_SCREENS: RegisteredScreen[] = Object.entries(SCREENS).map(
  ([id, { access, load }]) => ({ id, access, Component: lazy(load) })
);
