/**
 * Turns a real InvestorReport (all metrics computed from Postgres rows) into
 * downloadable PDF / Excel / CSV files. Shared by the admin dashboard and the
 * admin reports screens so the same numbers export everywhere.
 */
import type { InvestorReport } from "../api/types-compat";
import { Document, Footer, Header, ImageRun, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import { downloadPdf, downloadExcel, formatUGX } from "./export";

function kpiRows(r: InvestorReport): [string, string][] {
  return [
    ["Total customers", r.customers.total.toLocaleString()],
    ["Verified customers", r.customers.verified.toLocaleString()],
    ["New customers in period", r.customers.newThisMonth.toLocaleString()],
    ["Total loans", r.loans.total.toLocaleString()],
    ["Pending loans", r.loans.pending.toLocaleString()],
    ["Active loans", r.loans.active.toLocaleString()],
    ["Paid loans", r.loans.paid.toLocaleString()],
    ["Overdue loans", r.loans.overdue.toLocaleString()],
    ["Rejected loans", r.loans.rejected.toLocaleString()],
    ["Principal disbursed", formatUGX(r.loans.disbursedPrincipal)],
    ["Outstanding balance", formatUGX(r.loans.outstanding)],
    ["Total disbursed (cash out)", formatUGX(r.revenue.totalDisbursed)],
    ["Total collected (cash in)", formatUGX(r.revenue.totalCollected)],
    ["Realized interest revenue", formatUGX(r.revenue.realizedInterest)],
    ["Expected interest revenue", formatUGX(r.revenue.expectedInterest)],
    ["Default rate", `${r.ratios.defaultRatePct}%`],
    ["Repayment rate", `${r.ratios.repaymentRatePct}%`],
    ["Portfolio at risk (PAR)", `${r.ratios.parPct}%`],
  ];
}

function monthlyRows(r: InvestorReport): (string | number)[][] {
  return r.monthly.map((m) => [m.month, m.disbursed, m.collected, m.newCustomers]);
}

function subtitle(r: InvestorReport): string {
  return `${r.period.label} · generated ${new Date(r.generatedAt).toLocaleString("en-GB")} · by ${r.generatedBy || "Kuula staff"}`;
}

export async function exportInvestorReportPdf(r: InvestorReport): Promise<void> {
  await downloadPdf({
    title: "Investor Report",
    subtitle: subtitle(r),
    tables: [
      {
        title: "Key Performance Indicators",
        head: ["Metric", "Value"],
        rows: kpiRows(r),
      },
      {
        title: "Loan records",
        head: ["Date", "Customer", "Amount (UGX)", "Interest", "Status"],
        rows: r.rows.length ? r.rows.map(row => [new Date(row.date).toLocaleDateString("en-UG"), row.customer, row.amount.toLocaleString("en-UG"), row.interest.toLocaleString("en-UG"), row.status]) : [["No records for the selected period.", "", "", "", ""]],
      },
    ],
    meta: [{ label: "Period", value: r.period.label }, { label: "Generated by", value: r.generatedBy || "Kuula staff" }],
    filename: `kuula-loan-report-${reportStamp(r)}.pdf`,
  });
}

export function exportInvestorReportExcel(r: InvestorReport): void {
  downloadExcel(`kuula-loan-report-${reportStamp(r)}.xlsx`, [
    { name: "KPIs", rows: [["Metric", "Value"], ...kpiRows(r)] },
    {
      name: "Loans",
      rows: [
        ["Date", "Customer", "Amount (UGX)", "Interest (UGX)", "Status"],
        ...(r.rows.length ? r.rows.map(row => [new Date(row.date), row.customer, row.amount, row.interest, row.status]) : [["No records for the selected period.", "", "", "", ""]]),
      ],
    },
  ]);
}

function reportStamp(r: InvestorReport): string {
  return (r.period.start || r.generatedAt).slice(0, 7);
}

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a"); link.href = url; link.download = filename; link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function exportInvestorReportWord(r: InvestorReport): Promise<void> {
  const logo = await fetch("/kuula-icon-192.png").then(response => response.arrayBuffer()).catch(() => null);
  const headerChildren = [
    ...(logo ? [new ImageRun({ data: logo, transformation: { width: 42, height: 42 }, type: "png" })] : []),
    new TextRun({ text: " Kuula Microfinance Limited", bold: true, size: 28, color: "0B5E3A" }),
  ];
  const rows = r.rows.length ? r.rows.map(row => [new Date(row.date).toLocaleDateString("en-UG"), row.customer, String(row.amount), String(row.interest), row.status]) : [["No records for the selected period.", "", "", "", ""]];
  const table = new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [
    new TableRow({ tableHeader: true, children: ["Date", "Customer", "Amount (UGX)", "Interest (UGX)", "Status"].map(text => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })] })) }),
    ...rows.map(values => new TableRow({ children: values.map(text => new TableCell({ children: [new Paragraph(String(text))] })) })),
  ] });
  const doc = new Document({ sections: [{
    headers: { default: new Header({ children: [new Paragraph({ children: headerChildren })] }) },
    footers: { default: new Footer({ children: [new Paragraph(`Generated ${new Date(r.generatedAt).toLocaleString("en-UG")} by ${r.generatedBy || "Kuula staff"}`)] }) },
    children: [new Paragraph({ children: [new TextRun({ text: "Loan Report", bold: true, size: 36 })] }), new Paragraph(`Reporting period: ${r.period.label}`), new Paragraph(""), table],
  }] });
  saveBlob(await Packer.toBlob(doc), `kuula-loan-report-${reportStamp(r)}.docx`);
}
